version: '3.9'

services:
  backend:
    image: curtex19/redes2-backend
    container_name: backend-proyecto
    ports: 
      - '8080:8080'
    environment:
      - HOST=localhost
      - PORT=8080
      - NAME="api-node"
      - adminMongo=admin-g8
      - passwordMongo=redes2-p
      - hostMongo=54.152.33.31
    networks:
      - proyecto
  frontend:
    image: curtex19/redes2-frontend
    container_name: frontend-proyecto
    ports: 
      - '80:3000'
    environment:
      - REACT_APP_HOST=54.196.145.13
      - REACT_APP_PORT=8080
    depends_on:
      - backend
    networks:
      - proyecto
networks:
  proyecto:
    name: "proyecto"
    driver: bridge